### ISSUE TITLE
PVox Weapon Pickup Sound Bug

### ISSUE THREAD

**Issue by amneyxa** [kdgonz7/ImmPVox#16]
As stated before but is fixed, with another bug, it allows manual pick up which was fixed previous but a new issue has occured. The weapon pickup sound made by PVox is made when walking over a tool or weapon.

**Comment by kdgonz7** [comment]
What branch are you on? And do you have any other add ons that are not manual pickup, that you think could conflicting? That's super weird and I'll look at it. Do send a link to whatever addon you're having issues with

**Comment by amneyxa** [comment]
If you want to look at my collection to see what addons I have, [here](https://steamcommunity.com/sharedfiles/filedetails/?id=3290303084).  I currently play on the x86-64 branch, and I dont think I dont have any conflicts with PVox as of now.

**Comment by kdgonz7** [comment]
I currently can not reproduce this bug in my game.

**Comment by kdgonz7** [comment]
Does this just happen with the base game and "Manual Pickup" active?

**Comment by kdgonz7** [comment]
**UPDATE** I have been able to reproduce the bug and am working on a fix now.

**Comment by kdgonz7** [comment]
Fixed! Thanks for reporting.

**Comment by amneyxa** [comment]
What was it that caused it?

**Comment by kdgonz7** [comment]
It was an entire compatibility issue within PVox. When checking for pickups (in the player's area) VManip Manual Pickup would deny the request, but PVox still saw it as a valid run therefore it still tried to play the `pickup_weapon` action. The fix was to instead run the hook once before running the PVox one, and checking if there's nothing trying to deny the pickup. `_1` is the variable which prevents the PVox hook from running infinitely.

https://github.com/kdgonz7/ImmPVox/blob/09e3757f8975348946cd35399ced7fe45babfc2d/lua/autorun/playervox.lua#L1211-L1218

**Comment by kdgonz7** [comment]
(It says `PlayerCanPickupItem`, but same applies to weapons. This fix also added item pickup sounds)
